### ISSUE TITLE
Extracting the detected boxes as images "cropping"

### ISSUE THREAD

**Issue by ghost** [CommissarMa/pytorch-CRAFT#2]
@CommissarMa 
Will you consider adding the ability to extract the detected boxes.
Basically, crop the detected boxes and save each crop as an image.

**Comment by ghost** [comment]
This, I am sure you will have time for.

**Comment by CommissarMa** [comment]
yes, i will do this ability. but the box is polygon not rectangle, so i will use tranformation to make the text in the polygon to be horizontal. Then output it.



---Original---
