### ISSUE TITLE
训练效果

### ISSUE THREAD

**Issue by little2Rabbit** [CommissarMa/pytorch-CRAFT#3]
你好我训练了双层黄色车牌效果不是很好，双层黄色车牌是那种大卡车车牌，比如车牌上面是京A，下面是56G89。我训练得图片是把车牌直接裁剪下来，通过labelme标注，一共100张做训练，但是训练完每次识别都是整个车牌，我想检测车牌上面得京A，和下面得56G89。

**Comment by CommissarMa** [comment]
1、应该是用labelme一个字符一个字符进行矩形框标注。2、要加载预训练模型，然后进行训练。3、在1、2两步的基础上，观察region map和affinity map 的输出，然后调整后处理代码中关于分割的阈值，一般是调小点，就能按字符进行定位了。



---原始邮件---
发件人: "little2Rabbit"<notifications@github.com&gt;
发送时间: 2020年1月19日(周日) 上午8:44
收件人: "CommissarMa/pytorch-CRAFT"<pytorch-CRAFT@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [CommissarMa/pytorch-CRAFT] 训练效果 (#3)



你好我训练了双层黄色车牌效果不是很好，双层黄色车牌是那种大卡车车牌，比如车牌上面是京A，下面是56G89。我训练得图片是把车牌直接裁剪下来，通过labelme标注，一共100张做训练，但是训练完每次识别都是整个车牌，我想检测车牌上面得京A，和下面得56G89。
